{{- $secretName := include "getBackupSslSecretName" . }}
{{- if and $secretName .Values.backup.s3.enabled .Values.backup.s3.sslCert .Values.backup.s3.sslVerify (not (lookup "v1" "Secret" .Release.Namespace $secretName)) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  ca.crt: {{ .Values.backup.s3.sslCert | quote }}
{{- end }}
