{{- if eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true )) "true" }}
{{ $params := dict "isInternal" false}}
{{ $params = set $params "secret" (dict "secretName" .Values.dbaas.dbaasRegistrationSecretName "username" .Values.dbaas.dbaasAggregatorRegistrationUser "password" .Values.dbaas.dbaasAggregatorRegistrationPassword) }}
{{ $params = set $params "cloudPublicHost" .Values.CLOUD_PUBLIC_HOST }}
{{ $params = set $params "namespace" .Release.Namespace }}
{{ $params = set $params "serviceAccount" .Values.operator.operatorName }}
{{ $params = set $params "userEnv" .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME }}
{{ $params = set $params "passEnv" .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD }}
{{template "nosql.core.secret.fromEnv" $params }}
{{ end }}