{{- if (.Values.backup.install) }}
{{template "nosql.core.secret.internal" (dict "secret" (dict "secretName" .Values.backup.backupApiSecretName "username" .Values.backup.apiUser "password" .Values.backup.apiPassword) "cloudPublicHost" .Values.CLOUD_PUBLIC_HOST "namespace" .Release.Namespace "serviceAccount" .Values.operator.operatorName)}}
{{ end }}
