{{- if eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.prometheusExporter.install "envVar" .Values.MONITORING_ENABLED "default" true )) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prometheusExporter.prometheusExporterSecretName }}
  namespace: {{ .Release.Namespace }}
data:
  password: {{ default "admin" .Values.prometheusExporter.exporterPassword | b64enc }}
  username: {{ default "admin" .Values.prometheusExporter.exporterUser | b64enc }}
type: Opaque
  {{ end }}
