{{- if and .Values.robotTests.install .Values.robotTests.atpReport.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-robot-tests-atp-storage-secret
  labels:
    {{- include "mongodb.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  atp-storage-username: {{ .Values.robotTests.atpReport.atpStorage.username }}
  atp-storage-password: {{ .Values.robotTests.atpReport.atpStorage.password }}
{{- end }}
