{{- if and (.Values.backup.install) (and (not .Values.tls.generateCerts.enabled ) (ne (.Values.tls.mode) "disabled")) }}
kind: Secret
apiVersion: v1
metadata:
    name: {{ .Values.backup.tls.backupDaemonCASecretName }}
    namespace: {{ .Release.Namespace }}
data:
    {{ .Values.tls.rootCAFileName }}: {{ .Values.tls.certificates.ca_crt }}

    {{ .Values.tls.privateKeyFileName }}: {{ .Values.backup.tls.certificates.tls_key }}

    {{ .Values.tls.signedCRTFileName }}: {{ .Values.backup.tls.certificates.tls_crt }}
type: Opaque
{{ end }}