{{- if and (.Values.mongodb.install) (.Values.mongodb.pdb) (.Values.schemaSettings.sharded) }}

  {{- /* Dynamic quorum for shards */}}
  {{- $shardCount := .Values.schemaSettings.shardCount | int }}
  {{- $replicaSize := .Values.schemaSettings.dataReplicaSize | default 3 }}
  {{- $minAvailable := add (div $replicaSize 2) 1 }}

  {{- range $i, $ := until $shardCount }}
    {{- $index := add $i 1 }}
    {{- $shardName := printf "datars%d" $index }}
    {{- $labels := dict "app" "mongo-cluster" "microservice" $shardName }}
    {{- $pdbName := printf "pdb-%s" $shardName }}
    {{- template "nosql.core.pdb" (dict "name" $pdbName "labels" $labels "minAvailable" $minAvailable) }}
  {{- end }}

  {{- /* Config servers */}}
  {{- $cnfSize := .Values.schemaSettings.cnfReplicaSize | default 3 }}
  {{- $cnfMinAvailable := add (div $cnfSize 2) 1 }}
  {{- $cnfrLabels := dict "app" "mongo-cluster" "microservice" "cnfrs" }}
  {{- template "nosql.core.pdb" (dict "name" "pdb-cnfrs" "labels" $cnfrLabels "minAvailable" $cnfMinAvailable) }}

  {{/* Mongos */}}
  {{- if (eq .Values.schemaSettings.mongosReplicas 1) }}
    {{- $mongosLabels := dict "app" "mongo-cluster" "name" "mongos" }}
    {{- template "nosql.core.pdb" (dict "name" "pdb-mongos" "labels" $mongosLabels "minAvailable" 1) }}
  {{- end }}

{{- end }}

