{{ if .Values.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.operator.operatorName }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.operatorName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.operator.operatorName }}-{{ .Release.Namespace }}
{{ end }}
