apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-tests-config
  labels:
    app: mongo-tests
data:
  {{- if include "mongo.monitoredImages" . }}
  dd_images: {{ include "mongo.monitoredImages" . }}
  {{ else }}
  dd_images: ""
  {{ end }}