{{/* Generating deployment version each time */}}
{{- $deploymentVersion := randAlphaNum 10 -}}
apiVersion: netcracker.com/v1alpha1
kind: MongodbSupplService
metadata:
  name: {{ .Values.operator.operatorName }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  deploymentVersion: {{ $deploymentVersion | quote }}
  cloudPublicHost: {{ .Values.CLOUD_PUBLIC_HOST }}
  schemaSettings:
    schemaType: {{ .Values.schemaSettings.schemaType }}
    sharded: {{ .Values.schemaSettings.sharded }}
    cnfReplicaSize: {{template "fromEnv" (dict "envName" .Values.INFRA_MONGO_DB_REPLICAS "default" .Values.schemaSettings.cnfReplicaSize) }}
    dataReplicaSize: {{template "fromEnv" (dict "envName" .Values.INFRA_MONGO_DB_REPLICAS "default" .Values.schemaSettings.dataReplicaSize) }}
    shardCount: {{ .Values.schemaSettings.shardCount }}
    thisDomainName: {{ .Values.schemaSettings.thisDomainName }}
    {{- if .Values.schemaSettings.otherDomainName }}
    otherDomainName: {{ .Values.schemaSettings.otherDomainName }}
    {{- end }}

  imagePullPolicy: {{ .Values.imagePullPolicy }}

  recycler:
    {{- if eq .Values.schemaSettings.schemaType "dr" }}
    install: true
    {{- else }}
    install: {{ .Values.recycler.install }}
    {{- end }}
    resources:
      limits:
        memory: {{ .Values.recycler.resources.limits.memory }}
        cpu: {{ .Values.recycler.resources.limits.cpu | quote }}
      requests:
        memory: {{ .Values.recycler.resources.requests.memory }}
        cpu: {{ .Values.recycler.resources.requests.cpu | quote }}

  podSecurityContext:
    fsGroup: {{ .Values.podSecurityContext.fsGroup }}
    runAsUser: {{ .Values.podSecurityContext.runAsUser }}
    {{- if .Values.podSecurityContext.seLinuxOptions }}
    seLinuxOptions: {{ toYaml .Values.podSecurityContext.seLinuxOptions | nindent 6 }}
    {{- end }}
    {{- if .Values.supplementalGroups }}
    supplementalGroups:
      {{- range $key, $value := .Values.podSecurityContext.supplementalGroups }}
      - {{ $value | quote }}
      {{- end }}
    {{- end }}
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  {{- if .Values.policies }}
  policies:
    {{- if .Values.policies.tolerations }}
    tolerations:
      {{- range $tKey, $t := .Values.policies.tolerations }}
      - key: {{ $t.key }}
        effect: {{ $t.effect }}
        operator: {{ $t.operator }}
        tolerationSeconds: {{ $t.tolerationSeconds }}
        value: {{ $t.value }}
      {{- end }}
    {{- end }}
  {{- end }}

  deletePVConUninstall: {{ .Values.deletePVConUninstall }}

  waitSeconds: {{ .Values.waitSeconds }}
  authDb: {{ .Values.authDb }}
  ipV6: {{ .Values.ipV6 }}
  disasterRecovery:
    mode: {{ .Values.disasterRecovery.mode }}
  serviceAccountName: {{ .Values.operator.operatorName }}

  mongodb:
    install: {{ .Values.mongodb.install }}
    mongoRootSecretName: {{ .Values.mongodb.mongoRootSecretName }}

  backup:
    install: {{ .Values.backup.install }}
    storageDirectory: {{ .Values.backup.storageDirectory }}
    {{- if .Values.backup.s3.enabled }}
    s3:
      enabled: {{ .Values.backup.s3.enabled }}
      secretName: {{ .Values.backup.s3.secretName | quote }}
      bucketName: {{ .Values.backup.s3.bucketName | quote }}
      accessKeyId: {{ .Values.backup.s3.accessKeyId | quote }}
      accessKeySecret: {{ .Values.backup.s3.accessKeySecret | quote }}
      endpointUrl: {{ .Values.backup.s3.endpointUrl | quote }}
      sslVerify: {{ .Values.backup.s3.sslVerify }}
      sslSecretName: {{ .Values.backup.s3.sslSecretName | quote }}
      sslCert: {{ .Values.backup.s3.sslCert | quote }}
    {{- end }}
    {{- if ne (.Values.tls.mode) "disabled"}}
    tls:
      backupDaemonCASecretName: {{ .Values.backup.tls.backupDaemonCASecretName }}
    {{- end }}
    dockerImage: {{template "find_image" (dict "deployName" "backupDaemon" "SERVICE_NAME" "backupDaemon" "vals" .Values "default" .Values.backup.dockerImage) }}
    {{- if .Values.backup.priorityClassName }}
    priorityClassName: {{ .Values.backup.priorityClassName | quote }}
    {{- end }}
    {{- if .Values.backup.affinity }}
    affinity:
      {{- toYaml .Values.backup.affinity | nindent 6 }}
    {{- end }}
    {{- if .Values.backup.additionalNodeLabels }}
    additionalNodeLabels:
      {{- range $key, $value := .Values.backup.additionalNodeLabels }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    {{- end }}

    granularBackupSchedule: {{ .Values.backup.granularBackupSchedule }}
    {{- if .Values.backup.granularBackupScheduledDbs}}
    granularBackupScheduledDbs:
      {{- range $key, $value := .Values.backup.granularBackupScheduledDbs }}
      - {{ $value | quote }}
      {{- end }}
    {{- end }}
    backupSchedule: {{ .Values.backup.backupSchedule | quote }}
    incBackupSchedule: {{ .Values.backup.incBackupSchedule | quote }}
    evictionPolicy: {{ .Values.backup.evictionPolicy | quote }}
    incEvicitionPolicy: {{ .Values.backup.incEvicitionPolicy | quote}}
    mongoDatabasePrefixPattern: {{ .Values.backup.mongoDatabasePrefixPattern | quote }}
    backupApiSecretName: {{ .Values.backup.backupApiSecretName }}
    restoreUserSecretName: {{ .Values.backup.restoreUserSecretName }}
    backupSecretName: {{ .Values.backup.backupSecretName }}

    storage:
      emptyDir: {{ .Values.backup.storage.emptyDir }}
      {{- if eq "string" (printf "%T" .Values.backup.storage.size) }}
      size:
        - {{ .Values.backup.storage.size }}
      {{- else }}
      size:
        {{- range $key, $value := .Values.backup.storage.size }}
        - {{ $value | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.backup.storage.volumes }}
      volumes:
        {{- range $key, $value := .Values.backup.storage.volumes }}
        - {{ $value | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.backup.storage.nodeLabels }}
      nodeLabels:
        {{- range $key, $value := .Values.backup.storage.nodeLabels }}
          {{- $arraystart := "-" -}}
          {{- range $k, $v := $value }}
          {{ $arraystart }} {{ $k | quote }}: {{ $v | quote }}
          {{- $arraystart = " " }}
          {{- end }}
          {{- end }}
      {{- end }}
      {{- if .Values.backup.storage.storageClasses }}
      storageClasses:
        {{- range $key, $value := .Values.backup.storage.storageClasses }}
        - {{ $value | quote }}
        {{- end }}
      {{- else if .Values.STORAGE_RWO_CLASS }}
      storageClasses:
        - {{ .Values.STORAGE_RWO_CLASS | quote}}
      {{- else }}
      storageClasses:
        - ""
      {{- end }}
      {{- if .Values.backup.storage.matchLabelSelectors }}
      matchLabelSelectors:
        {{- range $key, $value := .Values.backup.storage.matchLabelSelectors }}
          {{- $arraystart := "-" -}}
          {{- range $k, $v := $value }}
          {{ $arraystart }} {{ $k | quote }}: {{ $v | quote }}
          {{- $arraystart = " " }}
          {{- end }}
          {{- end }}
      {{- end }}
      waitPvcBound: {{ .Values.backup.storage.waitPvcBound }}
      {{- if or .Values.pvc.metadata.annotations .Values.backup.storage.annotations }}
      annotations:
        {{- if .Values.pvc.metadata.annotations }}
        {{- toYaml .Values.pvc.metadata.annotations | nindent 8 }}
        {{- end }}
        {{- if .Values.backup.storage.annotations }}
        {{- toYaml .Values.backup.storage.annotations | nindent 8 }}
        {{- end }}
      {{- end }}
    backupResources:
      {{ template "getBackupResourcesForProfile" (dict "envVar" .Values.MONGODB_PROFILE "dotVar" .Values.global.profile "values" .Values) }}
    numParallelConnections: {{ .Values.backup.numParallelConnections }}
    granularNumParallelConnections: {{ .Values.backup.granularNumParallelConnections}}
    mongoSourceDB: {{ .Values.backup.mongoSourceDB | default "" | quote }}
    mongoBackupDB: {{ .Values.backup.mongoBackupDB | default "" | quote }}
    enableFullRestore: {{ .Values.backup.enableFullRestore }}
    dataValidationEnabled: {{ .Values.backup.dataValidationEnabled }}
    {{- if .Values.backup.configCollections }}
    configCollections:
      {{- range $key, $value := .Values.backup.configCollections }}
      - {{ $value | quote }}
      {{- end }}
    {{- end }}

  dbaas:
    install: {{template "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.dbaas.install "envVar" .Values.DBAAS_ENABLED "default" true ) }}
    dockerImage: {{template "find_image" (dict "deployName" "dbaas_mongo" "SERVICE_NAME" "dbaas_mongo" "vals" .Values "default" .Values.dbaas.dockerImage) }}
    {{- if .Values.dbaas.priorityClassName }}
    priorityClassName: {{ .Values.dbaas.priorityClassName | quote }}
    {{- end }}
    {{- if .Values.dbaas.affinity }}
    affinity:
      {{- toYaml .Values.dbaas.affinity | nindent 6 }}
    {{- end }}
    multiUsers: {{ .Values.dbaas.multiUsers }}
    dbaasAdminSecretName: {{ .Values.dbaas.dbaasAdminSecretName }}
    dbaasAggregatorSecretName: {{ .Values.dbaas.dbaasAggregatorSecretName }}
    dbaasRegistrationSecretName: {{ .Values.dbaas.dbaasRegistrationSecretName }}
    dbaasAdminRoleSecretName: {{ .Values.dbaas.dbaasAdminRoleSecretName }}
    {{- if ne (.Values.tls.mode) "disabled"}}
    tls:
      dbaasAdapterCASecretName: {{ .Values.dbaas.tls.dbaasAdapterCASecretName }}
    {{- end }}
    {{- if .Values.dbaas.additionalNodeLabels }}
    additionalNodeLabels:
      {{- range $key, $value := .Values.dbaas.additionalNodeLabels }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    dbaasAggregatorRegistrationAddress: {{template "fromEnv" (dict "envName" .Values.API_DBAAS_ADDRESS "default" .Values.dbaas.dbaasAggregatorRegistrationAddress) }}
    dbaasAggregatorRegistrationFixedDelayMS: {{ .Values.dbaas.dbaasAggregatorRegistrationFixedDelayMS }}
    dbaasAggregatorRegistrationRetryDelayMS: {{ .Values.dbaas.dbaasAggregatorRegistrationRetryDelayMS }}
    dbaasAggregatorRegistrationRetryTimeMS: {{ .Values.dbaas.dbaasAggregatorRegistrationRetryTimeMS }}
    {{- if .Values.dbaas.dbaasAggregatorPhysicalDatabaseIdentifier }}
    dbaasAggregatorPhysicalDatabaseIdentifier: {{ .Values.dbaas.dbaasAggregatorPhysicalDatabaseIdentifier }}
    {{- end }}
    {{- if .Values.dbaas.dbaasPhysicalDatabasesCustomLabels }}
    dbaasPhysicalDatabasesCustomLabels:
      {{- range $key, $value := .Values.dbaas.dbaasPhysicalDatabasesCustomLabels }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    {{- end }}

    dbaasResources:
      limits:
        memory: {{ .Values.dbaas.dbaasResources.limits.memory }}
        cpu: {{ .Values.dbaas.dbaasResources.limits.cpu | quote }}
      requests:
        memory: {{ .Values.dbaas.dbaasResources.requests.memory }}
        cpu: {{ .Values.dbaas.dbaasResources.requests.cpu | quote  }}

  prometheusExporter:
    install: {{template "fromValuesThenEnvElseDefault" (dict "dotVar" .Values.prometheusExporter.install "envVar" .Values.MONITORING_ENABLED "default" true ) }}
    dockerImage: {{template "find_image" (dict "deployName" "dockerPrometheusExporter" "SERVICE_NAME" "mongodb-prometheus-exporter" "vals" .Values "default" .Values.prometheusExporter.dockerImage) }}
    {{- if .Values.prometheusExporter.priorityClassName }}
    priorityClassName: {{ .Values.prometheusExporter.priorityClassName | quote }}
    {{- end }}
    monitoringSecretName: {{ .Values.prometheusExporter.monitoringSecretName }}
    prometheusExporterSecretName: {{ .Values.prometheusExporter.prometheusExporterSecretName }}
    {{- if .Values.prometheusExporter.additionalNodeLabels  }}
    additionalNodeLabels:
      {{- range $key, $value := .Values.prometheusExporter.additionalNodeLabels }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    exporterResources:
      limits:
        memory: {{ .Values.prometheusExporter.exporterResources.limits.memory }}
        cpu: {{ .Values.prometheusExporter.exporterResources.limits.cpu | quote }}
      requests:
        memory: {{ .Values.prometheusExporter.exporterResources.requests.memory }}
        cpu: {{ .Values.prometheusExporter.exporterResources.requests.cpu | quote }}

  robotTests:
    install: {{ .Values.robotTests.install }}
    dockerImage: {{template "find_image" (dict "deployName" "dockerRobotTests" "SERVICE_NAME" "mongo-tests" "vals" .Values "default" .Values.robotTests.dockerImage) }}
    {{- if .Values.robotTests.priorityClassName }}
    priorityClassName: {{ .Values.robotTests.priorityClassName | quote }}
    {{- end }}
    {{- if .Values.robotTests.affinity }}
    affinity:
      {{- toYaml .Values.robotTests.affinity | nindent 6 }}
    {{- end }}
    {{- if .Values.robotTests.tags }}
    tags: {{ .Values.robotTests.tags }}
    {{- else }}
    tags: "smokeORbackupORdbaasORmarker"
    {{- end }}
    mainSide: {{ .Values.robotTests.mainSide }}
    leftNodesPattern: {{ .Values.robotTests.leftNodesPattern }}
    rightNodesPattern: {{ .Values.robotTests.rightNodesPattern }}
    {{- if .Values.robotTests.externalBackupPath }}
    externalBackupPath: {{ .Values.robotTests.externalBackupPath }}
    {{- end }}
    {{- if .Values.robotTests.nodeLabels }}
    nodeLabels:
      {{- range $key, $value := .Values.robotTests.nodeLabels }}
      {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    resources:
      limits:
        cpu: {{ .Values.robotTests.resources.limits.cpu | quote }}
        memory: {{ .Values.robotTests.resources.limits.memory }}
      requests:
        cpu: {{ .Values.robotTests.resources.requests.cpu | quote }}
        memory: {{ .Values.robotTests.resources.requests.memory  }}
  tls:
    {{- if ne (.Values.tls.mode) "disabled"}}
    enabled: true
    {{- else}}
    enabled: false
    {{- end }}
    certificateSecretName: {{ .Values.tls.certificateSecretName }}
    rootCAFileName: {{ .Values.tls.rootCAFileName }}
    privateKeyFileName: {{ .Values.tls.privateKeyFileName }}
    signedCRTFileName: {{ .Values.tls.signedCRTFileName }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.operatorName }}
  labels:
    name: {{ .Values.operator.operatorName }}
    app.kubernetes.io/name: {{ .Values.operator.operatorName }}
    app.kubernetes.io/part-of: "mongodb-services"
    app.kubernetes.io/component: "operator"
    app.kubernetes.io/managed-by: "operator"
    app.kubernetes.io/managed-by-operator: "mongodb-services-operator"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/technology: "go"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.operator.operatorName }}
  template:
    metadata:
      labels:
        name: {{ .Values.operator.operatorName }}
        app.kubernetes.io/name: {{ .Values.operator.operatorName }}
        app.kubernetes.io/part-of: "mongodb-services"
        app.kubernetes.io/component: "operator"
        app.kubernetes.io/managed-by: "operator"
        app.kubernetes.io/managed-by-operator: "mongodb-services-operator"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/technology: "go"
    spec:
      serviceAccountName: {{ .Values.operator.operatorName }}
      priorityClassName: {{ .Values.operator.priorityClassName | quote }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Values.operator.operatorName }}
          # Replace this with the built image name
          image: {{template "find_image" (dict "deployName" "dockerMongodbService" "SERVICE_NAME" "dockerMongodbService" "vals" .Values "default" .Values.operator.image) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: healthz
              containerPort: 8081
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: RELEASE_NAME
              value: "{{ .Release.Name }}"
            - name: APP_VERSION
              value: "{{ .Chart.AppVersion }}"
            - name: CLOUD_PUBLIC_HOST
              value: {{ .Values.CLOUD_PUBLIC_HOST }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_ACCOUNT
              value: {{ .Values.operator.operatorName }}
            - name: RECONCILIATION_DELAY_SECONDS
              value: {{ .Values.crProcessingDelaySeconds | quote }}
            - name: MONGODB_OPERATOR_WAIT_DELAY_SECONDS
              value: {{ .Values.mongodbOperatorWaitDelaySeconds | default 30 | quote }}
            - name: DEPLOYMENT_VERSION
              value: {{ $deploymentVersion | quote }}
            - name: DEBUG_LOG
              value: {{ .Values.debugLog | quote }}
          {{- if ne (.Values.tls.mode) "disabled"}}
          volumeMounts: 
            - name:      root-ca
              mountPath: /usr/ssl/
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.operator.resources.requests.cpu }}
              memory: {{ .Values.operator.resources.requests.memory }}
            limits:
              cpu: {{ .Values.operator.resources.limits.cpu }}
              memory: {{ .Values.operator.resources.limits.memory }}
          livenessProbe:
              httpGet:
                path: /healthz
                port: 8081
              initialDelaySeconds: 15
              periodSeconds: 20
              timeoutSeconds: 2
              failureThreshold: 3
          readinessProbe:
              httpGet:
                path: /readyz
                port: 8081
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 3 
      {{- if ne (.Values.tls.mode) "disabled"}}
      volumes:
      - name: root-ca
        secret:
          secretName: {{ .Values.tls.certificateSecretName }}
      {{- end }}
      {{- if .Values.operator.affinity }}
      affinity:
        {{- toYaml .Values.operator.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.policies }}
      tolerations:
        {{- range $tKey, $t := .Values.policies.tolerations }}
        - key: {{ $t.key }}
          operator: {{ $t.operator }}
          value: {{ $t.value }}
          effect: {{ $t.effect }}
          tolerationSeconds: {{ $t.tolerationSeconds }}
      {{- end }}
  {{- end }}
