---
{{- if  (.Values.backup.s3.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backup.s3.secretName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
#    {{- if .Values.vaultRegistration.enabled }}
#    password: vault:{{ .Values.vaultRegistration.path }}/{{ .Values.backup.secretName }}#password
#    {{- else }}
#    {{- end }}
  username: {{ .Values.backup.s3.accessKeyId }}
  password: {{ .Values.backup.s3.accessKeySecret }}
type: Opaque
  {{ end }}
