---
{{- if  (.Values.backup.s3.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backup.s3.secretName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  S3_KEY_ID: {{ .Values.backup.s3.accessKeyId }}
  S3_KEY_SECRET: {{ .Values.backup.s3.accessKeySecret }}
type: Opaque
  {{ end }}
