{
 "title": "MongoDB 8 Prometheus",
 "description": "MongoDB Prometheus Exporter Dashboard.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(mongo_cluster_namespace)"
    }
   },
   {
    "name": "inter",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances_all",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_members_uptime, instance)"
    }
   },
   {
    "name": "data_set",
    "label": "Shards",
    "query": {
     "query": "label_values(mongodb_members_uptime{instance=~\"$instances_all\"}, instance)"
    }
   },
   {
    "name": "replica_sets",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_members_uptime{instance=~\"$instances_all\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "MongoDB Versions",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "avg by (instance,mongodb) (mongodb_version_info{namespace=\"$namespace\"})",
       "legendFormat": "{{mongodb}}"
      }
     ]
    },
    {
     "title": "Shards",
     "type": "stat",
     "description": "Total # of Shards in the Cluster",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(mongodb_mongos_sharding_shards_total{namespace=\"$namespace\"}) by (instance)"
      }
     ]
    },
    {
     "title": "Sharding databases",
     "type": "graph",
     "description": "Total # of Databases in the Cluster",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(mongodb_mongos_sharding_databases_total{namespace=\"$namespace\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Collections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(mongodb_mongos_db_collections_total{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Sharded collections",
     "type": "stat",
     "description": "Total # of Collections with Sharding enabled",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(mongodb_mongos_sharding_collections_total{namespace=\"$namespace\"}) by (instance)"
      }
     ]
    },
    {
     "title": "Mongos status",
     "type": "state-timeline",
     "description": "Show status of mongos",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mongodb_up{cluster=~\"$cluster\", namespace=\"$namespace\", instance=\"mongos\"}",
       "legendFormat": "{{instance}} - {{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "$replica_sets Primary",
     "type": "stat",
     "description": "Primary of the Shard",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 35 },
     "repeat": "replica_sets",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "label_replace(avg(mongodb_members_state{cluster=~\"$cluster\", namespace=\"$namespace\", instance=\"$replica_sets\"} == 1) by (instance, member_idx),\"short_name\", \"$1\", \"member_idx\", \"(.*)-0.*\")",
       "legendFormat": "{{short_name}}"
      }
     ]
    },
    {
     "title": "$replica_sets status",
     "type": "state-timeline",
     "description": "The Shard Replicas statuses",
     "gridPos": { "h": 4, "w": 21, "x": 3, "y": 35 },
     "repeat": "replica_sets",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(avg(mongodb_rs_members_state{cluster=~\"$cluster\", namespace=\"$namespace\", instance=\"$replica_sets\"}) by (instance, member_idx),\"short_name\", \"$1\", \"member_idx\", \"(.*)-0.*\")",
       "legendFormat": "{{short_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All Pods: Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O Utilization",
     "type": "timeseries",
     "description": "Shows data read/write in bytes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 215 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", container!~\"POD|\"}[5m])) by (namespace)",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum (rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", container!=\"\"}[5m])) by (namespace)",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Disk I/O Utilization By Pods",
     "type": "timeseries",
     "description": "Shows data read/write in bytes by pods",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 215 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", container!=\"\"}[5m])) by (pod)",
       "legendFormat": "reads: {{pod}}"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", container!=\"\"}[5m])) by (pod)",
       "legendFormat": "writes: {{pod}}"
      }
     ]
    },
    {
     "title": "Disk I/O Utilization By Pods",
     "type": "table",
     "description": "Shows data read/write in bytes by pods",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", container!=\"\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", container!=\"\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "IOps",
     "type": "timeseries",
     "description": "Count of writes/reads completed",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{namespace=\"$namespace\", container!~\"POD|\"}[5m])) ",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(rate(container_fs_writes_total{namespace=\"$namespace\", container!~\"POD|\"}[5m]))",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "IOps By Pods",
     "type": "timeseries",
     "description": "Count of writes/reads completed by pods",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{namespace=\"$namespace\", container!~\"POD|\"}[5m])) by (pod)",
       "legendFormat": "reads: {{pod}}"
      },
      {
       "expr": "sum(rate(container_fs_writes_total{namespace=\"$namespace\", container!~\"POD|\"}[5m])) by (pod)",
       "legendFormat": "writes: {{pod}}"
      }
     ]
    },
    {
     "title": "IOps By Pods",
     "type": "table",
     "description": "Count of writes/reads completed by pods",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{namespace=\"$namespace\", container!~\"POD|\"}[5m])) by (pod)",
       "legendFormat": "Reading"
      },
      {
       "expr": "sum(rate(container_fs_writes_total{namespace=\"$namespace\", container!~\"POD|\"}[5m])) by (pod)",
       "legendFormat": "Writing"
      }
     ]
    }
   ]
  },
  {
   "title": "All Pods: Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive/Transmit Bandwidth",
     "type": "timeseries",
     "description": "Shows the overall incoming and outgoing network traffic in bytes per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Receive/Transmit Bandwidth Usage By Pods",
     "type": "timeseries",
     "description": "Shows the overall incoming and outgoing network traffic in bytes per second by pods",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "receive: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "transmit: {{pod}}"
      }
     ]
    },
    {
     "title": "Receive/Transmit Bandwidth Usage By Pods",
     "type": "table",
     "description": "Shows the overall incoming and outgoing network traffic in bytes per second by pods",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[1m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[1m])) by (pod)"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets",
     "type": "timeseries",
     "description": "Shows the overall incoming and outgoing packets per second for the namespace",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Transmitted"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "Received Drops"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "Transmitted Drops"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets By Pods",
     "type": "timeseries",
     "description": "Shows the overall incoming and outgoing packets per second by pods for the namespace",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "receive: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "transmit: {{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted/Drops Packets By Pods",
     "type": "table",
     "description": "Shows overall incoming and outgoing network traffic in bytes per second by pods",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 262 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$namespace\"}[1m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$namespace\"}[1m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\"}[1m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\"}[1m])) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/RAM usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongos CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"mongos\",namespace=\"$namespace\"}[$inter])) by (pod)",
       "legendFormat": "Usage: {{pod}}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\", exported_pod=~\"mongos.*\"}",
       "legendFormat": "Limits: {{exported_pod}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_pod=~\"mongos.*\", exported_namespace=\"$namespace\"}) by (container, exported_pod)",
       "legendFormat": "Requests: {{exported_pod}}"
      }
     ]
    },
    {
     "title": "Mongos RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=\"mongos\"}) by (pod)",
       "legendFormat": "Usage: {{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", exported_pod=~\"mongos.*\"}) by (exported_pod)",
       "legendFormat": "Limits: {{exported_pod}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"mongos.*\", exported_namespace=\"$namespace\"}) by (exported_pod)",
       "legendFormat": "Requests: {{exported_pod}}"
      }
     ]
    },
    {
     "title": "$instances_all CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "repeat": "instances_all",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",io_kubernetes_container_name!=\"POD\",pod=~\"$instances_all.*\",namespace=\"$namespace\"}[$inter])) by (pod)",
       "legendFormat": "Usage: {{pod}}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\", exported_pod=~\"$instances_all.*\"}",
       "legendFormat": "Limits: {{exported_pod}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_pod=~\"$instances_all.*\", exported_namespace=\"$namespace\"}) by (container, exported_pod)",
       "legendFormat": "Requests: {{exported_pod}}"
      }
     ]
    },
    {
     "title": "$instances_all RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "repeat": "instances_all",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$instances_all.*\", image!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "Usage: {{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", exported_pod=~\"$instances_all.*\"}) by (exported_pod)",
       "legendFormat": "Limits: {{exported_pod}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"$instances_all.*\", exported_namespace=\"$namespace\"}) by (exported_pod)",
       "legendFormat": "Requests: {{exported_pod}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "avg(mongodb_memory{namespace=\"$namespace\", type=~\"resident|virtual\"}) by (instance, type)",
       "legendFormat": "{{instance}}: {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Amount of Collections in Shards",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max by (db,shard) (mongodb_mongos_db_collections_total{namespace=\"$namespace\", shard=~\"$data_set\"})",
       "legendFormat": "{{shard}}: {{db}}"
      }
     ]
    },
    {
     "title": "Top 10 largest DBs by data size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, avg by (db, shard) (mongodb_mongos_db_data_size_bytes{namespace=\"$namespace\", shard=~\"$data_set\"} ))",
       "legendFormat": "{{shard}}: {{db}}"
      }
     ]
    },
    {
     "title": "Top 10 largest DBs by storage size",
     "type": "timeseries",
     "description": "Sum of the space allocated to all collections in the database for document storage, including free space.\n\nThe \nstorageSize\n does not decrease as you remove or shrink documents.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "topk(10, mongodb_dbstats_storageSize{namespace=\"$namespace\", instance=~\"mongos.*\"})",
       "legendFormat": "{{instance}}: {{database}}"
      }
     ]
    },
    {
     "title": "DB data size $data_set",
     "type": "timeseries",
     "description": "Total size of the uncompressed data held in the database. The \ndataSize decreases when you remove documents.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "repeat": "data_set",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "mongodb_mongos_db_data_size_bytes{namespace=\"$namespace\", shard=\"$data_set\"}",
       "legendFormat": "{{db}}"
      }
     ]
    },
    {
     "title": "DB index size $data_set",
     "type": "graph",
     "description": "Sum of the space allocated to all indexes in the database, including free index space.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
     "repeat": "data_set",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongos_db_index_size_bytes{namespace=\"$namespace\", shard=\"$data_set\"}",
       "legendFormat": "{{db}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Detail",
     "type": "timeseries",
     "description": "Average latency of operations (classified by read, write, or (other) command)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 211 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (instance,type) (rate(mongodb_common_serverStatus_opLatencies_reads_latency{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) / (rate(mongodb_common_serverStatus_opLatencies_reads_ops{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) > 0) or irate(mongodb_common_serverStatus_opLatencies_reads_latency{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]) / (irate(mongodb_common_serverStatus_opLatencies_reads_ops{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]) > 0))",
       "legendFormat": "{{instance}}: reads"
      },
      {
       "expr": "avg by (instance,type) (rate(mongodb_common_serverStatus_opLatencies_writes_latency{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) / (rate(mongodb_common_serverStatus_opLatencies_writes_ops{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) > 0) or irate(mongodb_common_serverStatus_opLatencies_writes_latency{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]) / (irate(mongodb_common_serverStatus_opLatencies_writes_ops{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]) > 0))",
       "legendFormat": "{{instance}}: writes"
      },
      {
       "expr": "avg by (instance,type) (rate(mongodb_common_serverStatus_opLatencies_commands_latency{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) / (rate(mongodb_common_serverStatus_opLatencies_commands_ops{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) > 0) or irate(mongodb_common_serverStatus_opLatencies_commands_latency{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]) / (irate(mongodb_common_serverStatus_opLatencies_commands_ops{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]) > 0))",
       "legendFormat": "{{instance}}: commands"
      },
      {
       "expr": "avg by (instance,type) (rate(mongodb_mongod_op_latencies_latency_total{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) / (rate(mongodb_mongod_op_latencies_ops_total{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]) > 0))",
       "legendFormat": "{{instance}}: transactions"
      }
     ]
    },
    {
     "title": "Query Efficiency",
     "type": "timeseries",
     "description": "Ratio of Documents returned or Index entries scanned / full documents scanned\"",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 219 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(mongodb_common_serverStatus_metrics_queryExecutor_scanned{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval])) by (instance)/\r\nsum(rate(mongodb_common_serverStatus_metrics_queryExecutor_scannedObjects{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval])) by (instance) \r\nor\r\nsum(irate(mongodb_common_serverStatus_metrics_queryExecutor_scanned{namespace=\"$namespace\", instance=~\"$data_set\"}[5m])) by (instance)/\r\nsum(irate(mongodb_common_serverStatus_metrics_queryExecutor_scannedObjects{namespace=\"$namespace\", instance=~\"$data_set\"}[5m])) by (instance))",
       "legendFormat": "Index {{instance}}"
      },
      {
       "expr": "sum(rate(mongodb_mongod_metrics_document_total{namespace=\"$namespace\", instance=~\"$data_set\", state=\"returned\"}[$__interval]))  by (instance)/\r\nsum(rate(mongodb_mongod_metrics_query_executor_total{namespace=\"$namespace\", instance=~\"$data_set\", state=\"scanned_objects\"}[$__interval]))  by (instance) \r\nor\r\nsum(irate(mongodb_mongod_metrics_document_total{namespace=\"$namespace\", instance=~\"$data_set\", state=\"returned\"}[5m]))  by (instance)/\r\nsum(irate(mongodb_mongod_metrics_query_executor_total{namespace=\"$namespace\", instance=~\"$data_set\", state=\"scanned_objects\"}[5m]))  by (instance)",
       "legendFormat": "Document  {{instance}}"
      }
     ]
    },
    {
     "title": "Document Operations",
     "type": "timeseries",
     "description": "Docs per second inserted, updated, deleted or returned.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 228 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by (instance, state) (rate(mongodb_common_serverStatus_metrics_document_deleted{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) or \r\nirate(mongodb_common_serverStatus_metrics_document_deleted{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]))",
       "legendFormat": "{{instance}}: Deleted"
      },
      {
       "expr": "avg by (instance, state) (rate(mongodb_common_serverStatus_metrics_document_inserted{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) or \r\nirate(mongodb_common_serverStatus_metrics_document_inserted{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]))",
       "legendFormat": "{{instance}}: Inserted"
      },
      {
       "expr": "avg by (instance, state) (rate(mongodb_common_serverStatus_metrics_document_updated{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) or \r\nirate(mongodb_common_serverStatus_metrics_document_updated{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]))",
       "legendFormat": "{{instance}}: Updated"
      },
      {
       "expr": "avg by (instance,state) (rate(mongodb_mongod_metrics_document_total{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) or \r\nirate(mongodb_mongod_metrics_document_total{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]))",
       "legendFormat": "{{instance}}: Returned"
      }
     ]
    },
    {
     "title": "Scanned Objects",
     "type": "timeseries",
     "description": "This panel shows the number of objects (both data (scanned_objects) and index (scanned))",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 262 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by (instance,state) (rate(mongodb_common_serverStatus_metrics_queryExecutor_scanned{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) or \r\nirate(mongodb_common_serverStatus_metrics_queryExecutor_scanned{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]))",
       "legendFormat": "{{instance}}: Scanned"
      },
      {
       "expr": "avg by (instance, state) (rate(mongodb_mongod_metrics_query_executor_total{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]) or \r\nirate(mongodb_mongod_metrics_query_executor_total{namespace=\"$namespace\", instance=~\"$data_set\"}[5m]))",
       "legendFormat": "{{instance}}: ScannedObjects"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 270 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(mongodb_common_serverStatus_connections_current{namespace=\"$namespace\"}) by (instance, state)",
       "legendFormat": "{{instance}}: current"
      },
      {
       "expr": "avg(mongodb_connections{namespace=\"$namespace\", state=\"available\"}) by (instance, state)",
       "legendFormat": "{{instance}}: available"
      }
     ]
    },
    {
     "title": "Query Operations $data_set[$inter rate]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 278 },
     "repeat": "data_set",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(mongodb_common_serverStatus_opcounters_command{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval])) by (type)",
       "legendFormat": "command"
      },
      {
       "expr": "avg(rate(mongodb_common_serverStatus_opcounters_delete{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval])) by (type)",
       "legendFormat": "delete"
      },
      {
       "expr": "avg(rate(mongodb_common_serverStatus_opcounters_getmore{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval])) by (type)",
       "legendFormat": "getmore"
      },
      {
       "expr": "avg(rate(mongodb_common_serverStatus_opcounters_insert{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval])) by (type)",
       "legendFormat": "insert"
      },
      {
       "expr": "avg(rate(mongodb_common_serverStatus_opcounters_query{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval])) by (type)",
       "legendFormat": "query"
      },
      {
       "expr": "avg(rate(mongodb_op_counters_total{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval])) by (type)",
       "legendFormat": "update"
      }
     ]
    },
    {
     "title": "Page faults $data_set[$inter rate]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 278 },
     "repeat": "data_set",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(rate(mongodb_extra_info_page_faults_total{namespace=\"$namespace\", instance=~\"$data_set\"}[$inter])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MongoDB Assertions per [$inter rate]",
     "type": "timeseries",
     "description": "MongoDB Assertions rate",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 285 },
     "targets": [
      {
       "expr": "rate(mongodb_common_serverStatus_asserts_msg{namespace=\"$namespace\"}[$inter])",
       "legendFormat": "{{instance}}:msg"
      },
      {
       "expr": "rate(mongodb_common_serverStatus_asserts_regular{namespace=\"$namespace\"}[$inter])",
       "legendFormat": "{{instance}}:regular"
      },
      {
       "expr": "rate(mongodb_common_serverStatus_asserts_rollovers{namespace=\"$namespace\"}[$inter])",
       "legendFormat": "{{instance}}:rollovers"
      },
      {
       "expr": "rate(mongodb_common_serverStatus_asserts_tripwire{namespace=\"$namespace\"}[$inter])",
       "legendFormat": "{{instance}}:tripwire"
      },
      {
       "expr": "rate(mongodb_common_serverStatus_asserts_user{namespace=\"$namespace\"}[$inter])",
       "legendFormat": "{{instance}}:user"
      },
      {
       "expr": "rate(mongodb_asserts_total{namespace=\"$namespace\"}[$inter])",
       "legendFormat": "{{instance}}:warning"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(mongodb_oplog_stats_storageStats_count{namespace=\"$namespace\", cluster=~\"$cluster\"}) by (instance, cluster)",
       "legendFormat": "{{instance}} - {{cluster}}"
      }
     ]
    },
    {
     "title": "Oplog Recovery Window",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (instance,cluster) (mongodb_mongod_replset_oplog_head_timestamp{namespace=\"$namespace\",cluster=~\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{namespace=\"$namespace\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} - {{cluster}}"
      }
     ]
    },
    {
     "title": "Elections",
     "type": "timeseries",
     "description": "Count of elections. Usually zero; 1 count by each healthy node will appear in each election. Happens when the primary role changes due to either normal maintenance or trouble events.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (instance) (changes(mongodb_mongod_replset_member_election_date{namespace=\"$namespace\", instance=~\"$data_set\"}[$__interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Oplog Recovery Window",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (instance,cluster) (mongodb_mongod_replset_oplog_head_timestamp{namespace=\"$namespace\",cluster=~\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{namespace=\"$namespace\",cluster=~\"$cluster\"})",
       "legendFormat": "{{instance}} - {{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DBaaS adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "state-timeline",
     "description": "Shows DBaaS Adapter status",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(min(container_start_time_seconds{namespace=\"$namespace\", container!=\"POD\", container=~\"dbaas-mongo-adapter\"}) by (pod)/min(container_start_time_seconds{namespace=\"$namespace\", container!=\"POD\", container=~\"dbaas-mongo-adapter\"}) by (pod))",
       "legendFormat": "{{replica}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Shows CPU usage per container in pod against resource requests and limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum by (namespace, pod, container)(\rrate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"dbaas-mongo-adapter\"}[$inter]))) by (container, pod)",
       "legendFormat": "Usage: {{ pod }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=\"$namespace\", container=~\"dbaas-mongo-adapter\"}) by (container, exported_pod)\n",
       "legendFormat": "Requests: {{ exported_pod }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\", container=~\"dbaas-mongo-adapter\"}) by (container, exported_pod)\n",
       "legendFormat": "Limits: {{ exported_pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Shows memory usage per container in pod against resource requests and limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=~\"dbaas-mongo-adapter\", image!=\"\"}) by (container, pod)",
       "legendFormat": "Usage: {{pod}}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests_memory_bytes{exported_namespace=\"$namespace\", container=~\"dbaas-mongo-adapter\"}) by (exported_pod)\n",
       "legendFormat": "Requests: {{ exported_pod }}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=~\"dbaas-mongo-adapter\"}) by (exported_pod)\n",
       "legendFormat": "Limits: {{exported_pod}}"
      }
     ]
    },
    {
     "title": "GC Duration",
     "type": "timeseries",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=\"$namespace\",job=~\"dbaas-mongo-adapter\",quantile=\"0.75\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "The current number of threads",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_threads{namespace=\"$namespace\",job=~\"dbaas-mongo-adapter\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Requests Count",
     "type": "timeseries",
     "description": "The total number of requests DBaaS Adapter received per response status",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(sum by (pod, status_code)(\r\nincrease(requests_total{namespace=\"$namespace\",job=~\"dbaas-mongo-adapter\"}[1m]))) by (pod, status_code)",
       "legendFormat": "Status: {{status_code}}"
      }
     ]
    },
    {
     "title": "DBaaS API Requests Duration",
     "type": "timeseries",
     "description": "The requests duration per each DBaaS Adapter endpoint",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(label_replace(rate(request_duration_seconds_sum{namespace=\"$namespace\"}[$inter]) / rate(request_duration_seconds_count{namespace=\"$namespace\"}[$inter]),\"urit\",\"$1\",\"path\",\".*mongo(\\\\/\\\\w+).*\")) by (method, urit)",
       "legendFormat": "{{method}}: {{urit}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup daemon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "state-timeline",
     "description": "Shows Backup Adapter status",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(min(container_start_time_seconds{namespace=\"$namespace\", container!=\"POD\", container=~\"mongodb-backup-daemon\"}) by (pod)/min(container_start_time_seconds{namespace=\"$namespace\", container!=\"POD\", container=~\"mongodb-backup-daemon\"}) by (pod))",
       "legendFormat": "{{replica}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Shows CPU usage per container in pod against resource requests and limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum by (namespace, pod, container)(\rrate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"mongodb-backup-daemon\"}[$inter]))) by (container, pod)",
       "legendFormat": "Usage: {{ pod }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_namespace=\"$namespace\", container=~\"mongodb-backup-daemon\"}) by (container, exported_pod)\n",
       "legendFormat": "Requests: {{ exported_pod }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\", container=~\"mongodb-backup-daemon\"}) by (container, exported_pod)\n",
       "legendFormat": "Limits: {{ exported_pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Shows memory usage per container in pod against resource requests and limits",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=~\"mongodb-backup-daemon\", image!=\"\"}) by (pod)",
       "legendFormat": "Usage: {{pod}}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests_memory_bytes{exported_namespace=\"$namespace\", container=~\"mongodb-backup-daemon\"}) by (exported_pod)\n",
       "legendFormat": "Requests: {{ exported_pod }}"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=~\"mongodb-backup-daemon\"}) by (exported_pod)\n",
       "legendFormat": "Limits: {{exported_pod}}"
      }
     ]
    },
    {
     "title": "Status",
     "type": "state-timeline",
     "description": "Shows Last Backup status",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(backup_storage_last_failed{namespace=\"$namespace\", job=~\"mongodb-backup-daemon\"})",
       "legendFormat": "{{replica}}"
      }
     ]
    },
    {
     "title": "Last Backup Size",
     "type": "timeseries",
     "description": "Size of last successful backup ",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "backup_storage_last_successful_size{namespace=\"$namespace\",job=~\"mongodb-backup-daemon\"}",
       "legendFormat": "ID: {{id}}"
      }
     ]
    },
    {
     "title": "Dumps count",
     "type": "timeseries",
     "description": "Current number of dumps",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "backup_storage_dump_count{namespace=\"$namespace\",job=~\"mongodb-backup-daemon\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Storage Space Usage",
     "type": "timeseries",
     "description": "Shows used by backups space against total space",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "backup_storage_size{namespace=\"$namespace\",job=~\"mongodb-backup-daemon\"}",
       "legendFormat": "Usage"
      },
      {
       "expr": "backup_storage_space_total{namespace=\"$namespace\",job=~\"mongodb-backup-daemon\"}\n",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Storage Inodes Usage",
     "type": "timeseries",
     "description": "Shows inodes usage",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "backup_storage_used_inodes{namespace=\"$namespace\",job=~\"mongodb-backup-daemon\"}",
       "legendFormat": "Usage"
      },
      {
       "expr": "backup_storage_inodes_total{namespace=\"$namespace\",job=~\"mongodb-backup-daemon\"}\n",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  }
 ]
}