//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/Netcracker/qubership-nosqldb-operator-core/pkg/types"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Backup) DeepCopyInto(out *Backup) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = (*in).DeepCopy()
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigCollections != nil {
		in, out := &in.ConfigCollections, &out.ConfigCollections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalNodeLabels != nil {
		in, out := &in.AdditionalNodeLabels, &out.AdditionalNodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.S3 = in.S3
	out.TLS = in.TLS
	if in.GranularBackupScheduledDbs != nil {
		in, out := &in.GranularBackupScheduledDbs, &out.GranularBackupScheduledDbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backup.
func (in *Backup) DeepCopy() *Backup {
	if in == nil {
		return nil
	}
	out := new(Backup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupDaemonTLS) DeepCopyInto(out *BackupDaemonTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupDaemonTLS.
func (in *BackupDaemonTLS) DeepCopy() *BackupDaemonTLS {
	if in == nil {
		return nil
	}
	out := new(BackupDaemonTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dbaas) DeepCopyInto(out *Dbaas) {
	*out = *in
	if in.AdditionalNodeLabels != nil {
		in, out := &in.AdditionalNodeLabels, &out.AdditionalNodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.DbaasPhysicalDatabasesCustomLabels != nil {
		in, out := &in.DbaasPhysicalDatabasesCustomLabels, &out.DbaasPhysicalDatabasesCustomLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.TLS = in.TLS
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dbaas.
func (in *Dbaas) DeepCopy() *Dbaas {
	if in == nil {
		return nil
	}
	out := new(Dbaas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbaasAdapterTLS) DeepCopyInto(out *DbaasAdapterTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbaasAdapterTLS.
func (in *DbaasAdapterTLS) DeepCopy() *DbaasAdapterTLS {
	if in == nil {
		return nil
	}
	out := new(DbaasAdapterTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterRecovery) DeepCopyInto(out *DisasterRecovery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterRecovery.
func (in *DisasterRecovery) DeepCopy() *DisasterRecovery {
	if in == nil {
		return nil
	}
	out := new(DisasterRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDB) DeepCopyInto(out *MongoDB) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDB.
func (in *MongoDB) DeepCopy() *MongoDB {
	if in == nil {
		return nil
	}
	out := new(MongoDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbSupplService) DeepCopyInto(out *MongodbSupplService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbSupplService.
func (in *MongodbSupplService) DeepCopy() *MongodbSupplService {
	if in == nil {
		return nil
	}
	out := new(MongodbSupplService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongodbSupplService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbSupplServiceList) DeepCopyInto(out *MongodbSupplServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MongodbSupplService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbSupplServiceList.
func (in *MongodbSupplServiceList) DeepCopy() *MongodbSupplServiceList {
	if in == nil {
		return nil
	}
	out := new(MongodbSupplServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongodbSupplServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbSupplServiceSpec) DeepCopyInto(out *MongodbSupplServiceSpec) {
	*out = *in
	out.MongoDB = in.MongoDB
	in.Backup.DeepCopyInto(&out.Backup)
	in.Dbaas.DeepCopyInto(&out.Dbaas)
	in.PrometheusExporter.DeepCopyInto(&out.PrometheusExporter)
	in.RobotTests.DeepCopyInto(&out.RobotTests)
	out.TLS = in.TLS
	in.Recycler.DeepCopyInto(&out.Recycler)
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(Policies)
		(*in).DeepCopyInto(*out)
	}
	out.SchemaSettings = in.SchemaSettings
	if in.DisasterRecovery != nil {
		in, out := &in.DisasterRecovery, &out.DisasterRecovery
		*out = new(DisasterRecovery)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbSupplServiceSpec.
func (in *MongodbSupplServiceSpec) DeepCopy() *MongodbSupplServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MongodbSupplServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongodbSupplServiceStatus) DeepCopyInto(out *MongodbSupplServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]types.ServiceStatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongodbSupplServiceStatus.
func (in *MongodbSupplServiceStatus) DeepCopy() *MongodbSupplServiceStatus {
	if in == nil {
		return nil
	}
	out := new(MongodbSupplServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Policies) DeepCopyInto(out *Policies) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Policies.
func (in *Policies) DeepCopy() *Policies {
	if in == nil {
		return nil
	}
	out := new(Policies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusExporter) DeepCopyInto(out *PrometheusExporter) {
	*out = *in
	if in.AdditionalNodeLabels != nil {
		in, out := &in.AdditionalNodeLabels, &out.AdditionalNodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusExporter.
func (in *PrometheusExporter) DeepCopy() *PrometheusExporter {
	if in == nil {
		return nil
	}
	out := new(PrometheusExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtpReport) DeepCopyInto(out *AtpReport) {
	*out = *in
	out.AtpStorage = in.AtpStorage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtpReport.
func (in *AtpReport) DeepCopy() *AtpReport {
	if in == nil {
		return nil
	}
	out := new(AtpReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtpStorage) DeepCopyInto(out *AtpStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtpStorage.
func (in *AtpStorage) DeepCopy() *AtpStorage {
	if in == nil {
		return nil
	}
	out := new(AtpStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotTests) DeepCopyInto(out *RobotTests) {
	*out = *in
	in.AtpReport.DeepCopyInto(&out.AtpReport)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotTests.
func (in *RobotTests) DeepCopy() *RobotTests {
	if in == nil {
		return nil
	}
	out := new(RobotTests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3backup) DeepCopyInto(out *S3backup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3backup.
func (in *S3backup) DeepCopy() *S3backup {
	if in == nil {
		return nil
	}
	out := new(S3backup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaSettings) DeepCopyInto(out *SchemaSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaSettings.
func (in *SchemaSettings) DeepCopy() *SchemaSettings {
	if in == nil {
		return nil
	}
	out := new(SchemaSettings)
	in.DeepCopyInto(out)
	return out
}
