{{- if eq (include "fromValuesThenEnvElseDefault" (dict "dotVar" (default dict .Values.prometheusExporter).install "envVar" .Values.MONITORING_ENABLED "default" true)) "true" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    prometheus: {{ .Release.Namespace }}-tls-static-metrics-rules
    role: record-rules
  name: {{ .Release.Namespace }}-tls-static-metrics-rules
spec:
  groups:
    - name: {{ .Release.Namespace }}-{{ .Release.Name }}
      rules:
        {{- include "global.tlsStaticMetric" (dict "namespace" .Release.Namespace "application" "mongodb" "service" "Mongodb" "enabledSsl" (ne .Values.tls.mode "disabled") "secret" .Values.tls.rootCASecretName "certProvider" "cert-manager" "certificate" "mongodb-tls-certificate") | nindent 8 }}
{{- end }}
