{{- if and (eq .Values.schemaSettings.schemaType "dr") (and (not .Values.tls.generateCerts.enabled ) (ne (.Values.tls.mode) "disabled"))}}
kind: Secret
apiVersion: v1
metadata:
    name: {{ .Values.disasterRecovery.tls.drCASecretName }}
    namespace: {{ .Release.Namespace }}
data:
    {{ .Values.tls.rootCAFileName }}: {{ .Values.tls.certificates.ca_crt }}

    {{ .Values.tls.privateKeyFileName }}: {{ .Values.disasterRecovery.tls.certificates.tls_key }}

    {{ .Values.tls.signedCRTFileName }}: {{ .Values.disasterRecovery.tls.certificates.tls_crt }}
type: Opaque
{{ end }}