{{- if .Values.vaultRegistration }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mongodb-operator
  name: {{ .Values.vaultRegistration.tokenSecretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  {{- if .Values.VAULT_TOKEN }}
  token: {{ .Values.VAULT_TOKEN | b64enc }}
  {{- else }}
  token: {{ default "#" .Values.vaultRegistration.token | b64enc }}
  {{- end }}
type: Opaque
{{- end }}