name: Branch Deleted
on: delete

env:
  COMPONENT_NAME: qubership-mongodb-operator
  TAG_NAME: ${{ github.event.ref }}

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-mongodb-operator
            context: ""
          - name: qubership-mongodb-operator-transfer
            context: ""
          - name: mongodb-supplementary
            context: ""
          - name: mongodb-supplementary-transfer
            context: ""
          - name: mongodb-docker-tests
            context: ""
          - name: mongodb-docker-backup-daemon
            context: ""
          - name: mongodb-docker-dbaas-adapter
            context: ""
          - name: mongodb-docker-prometheus-exporter
            context: ""
          - name: docker-mongo-7
            context: ""
          - name: docker-mongo-8
            context: ""
    steps:
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@84bc8eb8bed50218be76e671b3a24c35a1300979
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete != '' }}