name: Run Nightly MongoDB Pipeline

permissions:
  contents: read
  packages: read
  actions: read

on:
  push
#  schedule:
#    - cron: '0 1 * * *'

jobs:
  Nightly-MongoDB-Pipeline:
    uses: Netcracker/qubership-test-pipelines/.github/workflows/mongodb.yaml@df5060a6cd932b5560c285d00307d7792f056c0d # v1.17.1
    with:
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: 'df5060a6cd932b5560c285d00307d7792f056c0d' # v1.17.1 renovate: depName=Netcracker/qubership-test-pipelines
      runner_type: 'ubuntu-latest'
      scope: 'nightly'
      allure: true
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
